# Generated by Django 3.1.3 on 2020-11-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='UserId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Type',
            field=models.CharField(choices=[(models.CharField(max_length=200), 'Text'), ('OC', 'OneChoice'), ('MC', 'ManyChoice')], default=models.CharField(max_length=200), max_length=2),
        ),
    ]
